### ISSUE TITLE
Server status not working since latest update

### ISSUE THREAD

**Issue by tdgPLS** [Andrew1175/Palworld-Dedicated-Server-Manager#3]
Palworld server file is now "PalServer-Win64-Shipping-Cmd.exe" instead of "PalServer-Win64-Test-Cmd.exe" so Palworld Dedicated Server Manager doesn't detect it's running and restarts it causing a new instance to be launched every five minutes by default, it's also not able to detect if the server is online or shut it down gracefully or forcefully.

**Comment by Andrew1175** [comment]
Working on this today. Should have a release soon.

**Comment by Andrew1175** [comment]
This is now fixed in [version 1.4.0](https://github.com/Andrew1175/Palworld-Dedicated-Server-Manager/releases/tag/v1.4.0)
